name: Daily GitHub Contributor

on:
  schedule:
    # 每天 UTC 時間上午 9 點執行。
    # 例如，如果你在台灣（UTC+8），這表示每天下午 5 點執行。
    # 如果你想調整時間，可以修改 '0 9 * * *'
    # 格式是：分鐘 小時 月份中的日期 月份 星期幾
    # 例如：'30 1 * * *' 表示每個月的 1 號 1 點 30 分
    - cron: '0 9 * * *'
  workflow_dispatch: # 允許你手動從 GitHub 網頁觸發這個工作流程

jobs:
  daily_commit:
    runs-on: ubuntu-latest # 在最新的 Ubuntu 系統上運行

    steps:
    - name: Checkout repository # 步驟1: 把你的倉庫內容下載下來
      uses: actions/checkout@v4

    - name: Set up Python # 步驟2: 準備 Python 環境
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # 使用最新的 Python 3 版本

    - name: Run daily commit script # 步驟3: 執行你的 Python 腳本
      run: |
        python daily_commit.py

      env:
        # GitHub Actions 會自動提供一個 Token，讓你的腳本有權限推送程式碼
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
